//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourSensei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTrackCategory
    {
        public int TrackId { get; set; }
        public System.Guid UserID { get; set; }
        public string TrackName { get; set; }
        public string CategorySequesnce { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
    }
}
