//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourSensei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public System.Guid ID { get; set; }
        public string companyname { get; set; }
        public string websiteaddress { get; set; }
        public string email { get; set; }
        public int programcount { get; set; }
        public int peoplecount { get; set; }
        public string LogoUrl { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
    }
}
