//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourSensei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLibraryBookLogTransaction
    {
        public int ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public int CompanyLibraryBookLogsID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> AcceptedBy { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
    }
}
