//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourSensei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySetting
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyId { get; set; }
        public bool IsMentorMandatory { get; set; }
        public bool GlobalAverageBookRating { get; set; }
        public bool GlobalMentor { get; set; }
        public bool GlobalBookList { get; set; }
        public System.Guid A3DollarApprover { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
