//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourSensei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizStatu
    {
        public int ID { get; set; }
        public System.Guid UserdetailID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public System.Guid CompanyLibraryBookID { get; set; }
        public int QuizID { get; set; }
        public bool IsQuizStarted { get; set; }
        public bool IsQuizFinished { get; set; }
    }
}
