//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourSensei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int ID { get; set; }
        public int PlanID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> UserDetailID { get; set; }
        public System.DateTime PurchasedDate { get; set; }
        public System.Guid PurchasedBy { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.Guid> RenewedBy { get; set; }
        public bool IsActivated { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public System.Guid ActivatedBy { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool IsExpired { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
