//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourSensei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlanHistory
    {
        public int ID { get; set; }
        public int PlanID { get; set; }
        public string PlanObject { get; set; }
        public string Action { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModififedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
