//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolveBeltProgressApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRead
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid UserDetailID { get; set; }
        public System.Guid BookID { get; set; }
        public System.DateTime Completeddate { get; set; }
        public int Rating { get; set; }
        public string Comments { get; set; }
    }
}
