//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolveBeltProgressApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditLog
    {
        public System.Guid ID { get; set; }
        public string MemberID { get; set; }
        public System.Guid UserDetailID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.Guid CompanyID { get; set; }
        public string Description { get; set; }
        public System.Guid KeyID { get; set; }
        public string KeyType { get; set; }
        public System.DateTime AwardedDate { get; set; }
        public decimal Credit { get; set; }
    }
}
