//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolveBeltProgressApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid ID { get; set; }
        public string MemberID { get; set; }
        public System.Guid UserRoleID { get; set; }
        public string OtherRole { get; set; }
        public Nullable<System.Guid> MentorId { get; set; }
        public bool IsExternalMentor { get; set; }
        public System.Guid CompanyId { get; set; }
        public bool IsMentor { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public decimal CreditScore { get; set; }
        public string EmployeeCode { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string Gender { get; set; }
    }
}
