//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolveBeltProgressApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionTransaction
    {
        public int ID { get; set; }
        public int PlanID { get; set; }
        public int SubscriptionID { get; set; }
        public decimal Payment { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionStatus { get; set; }
        public string TransactionID { get; set; }
        public string TransactionMode { get; set; }
        public int PaymentCardDetailID { get; set; }
    }
}
