//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolveBeltProgressApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingEventA3Diagram
    {
        public int ID { get; set; }
        public System.Guid TrainingEventID { get; set; }
        public System.Guid AssignedTo { get; set; }
        public string Background { get; set; }
        public string Proposal { get; set; }
        public string CurrentCondition { get; set; }
        public string Plan { get; set; }
        public string Goal { get; set; }
        public string FollowUp { get; set; }
        public string Analyses { get; set; }
        public decimal DollarImpacted { get; set; }
        public bool IsDollarValueApproved { get; set; }
        public System.DateTime DollarValueApprovedDate { get; set; }
        public System.Guid DollarValueApprovedBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Modifieddate { get; set; }
        public System.Guid ModifiedBy { get; set; }
    }
}
