//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolveBeltProgressApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingEvent
    {
        public System.Guid ID { get; set; }
        public System.Guid owner { get; set; }
        public string bannerimageurl { get; set; }
        public string Name { get; set; }
        public string location { get; set; }
        public Nullable<System.Guid> instructor { get; set; }
        public string duration { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime plannedtrainingdate { get; set; }
        public System.Guid responsibletrainer { get; set; }
        public string trainingdescription { get; set; }
        public System.Guid TrainingEventFormatID { get; set; }
        public string trainingnotes { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> UserDetailID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public Nullable<bool> Isclosed { get; set; }
        public string ClosingNote { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.Guid> ClosedBy { get; set; }
        public string Status { get; set; }
    }
}
